### ISSUE TITLE
Reproducing the results

### ISSUE THREAD

**Issue by funnypig521** [Vegetebird/MHFormer#10]
Excuse me, I can not reproduce your results.For 81 frames, I can only achieve 44.83mm MPJPE, and for 351 frame, just 43.17mm.Would you please tell me the reason or show me the way to revisit results? It would be better if you could share the training log.Thanks a lot!!!

**Comment by funnypig521** [comment]
@alecda573 They are both for CPN detections.Here are my training logs and test results for 81 frames.Could you please explain more specifically？
2022/03/23 16:55:35 epoch: 1, lr: 0.0010000, loss: 0.0516, mpjpe: 49.42
2022/03/23 18:00:17 epoch: 2, lr: 0.0009500, loss: 0.0348, mpjpe: 45.19
2022/03/23 19:05:02 epoch: 3, lr: 0.0009025, loss: 0.0320, mpjpe: 45.65
2022/03/23 20:09:48 epoch: 4, lr: 0.0008574, loss: 0.0307, mpjpe: 45.45
2022/03/23 21:14:32 epoch: 5, lr: 0.0008145, loss: 0.0299, mpjpe: 44.95
2022/03/23 22:19:18 epoch: 6, lr: 0.0004073, loss: 0.0285, mpjpe: 45.12
2022/03/23 23:24:02 epoch: 7, lr: 0.0003869, loss: 0.0282, mpjpe: 45.14
2022/03/24 00:28:50 epoch: 8, lr: 0.0003675, loss: 0.0280, mpjpe: 45.13
2022/03/24 01:32:58 epoch: 9, lr: 0.0003492, loss: 0.0278, mpjpe: 45.34
2022/03/24 02:37:06 epoch: 10, lr: 0.0003317, loss: 0.0276, mpjpe: 44.83
2022/03/24 03:41:13 epoch: 11, lr: 0.0001659, loss: 0.0272, mpjpe: 45.58
2022/03/24 04:45:19 epoch: 12, lr: 0.0001576, loss: 0.0271, mpjpe: 45.67
2022/03/24 05:49:27 epoch: 13, lr: 0.0001497, loss: 0.0269, mpjpe: 45.00
2022/03/24 06:53:33 epoch: 14, lr: 0.0001422, loss: 0.0269, mpjpe: 45.43
2022/03/24 07:57:39 epoch: 15, lr: 0.0001351, loss: 0.0268, mpjpe: 45.69
2022/03/24 09:01:57 epoch: 16, lr: 0.0000675, loss: 0.0267, mpjpe: 45.18
2022/03/24 10:06:42 epoch: 17, lr: 0.0000642, loss: 0.0266, mpjpe: 46.29
2022/03/24 11:11:26 epoch: 18, lr: 0.0000610, loss: 0.0265, mpjpe: 46.06
2022/03/24 12:16:10 epoch: 19, lr: 0.0000579, loss: 0.0265, mpjpe: 46.02
2022/03/24 13:20:56 epoch: 20, lr: 0.0000550, loss: 0.0266, mpjpe: 47.05

100%|███████████████████████████████████████| 4245/4245 [08:32<00:00,  8.28it/s]
===Action=== ==MPJPE===
Directions     41.13
Discussion     45.84
Eating         41.87
Greeting       43.21
Phoning        45.91
Photo          51.45
Posing         42.38
Purchases      42.51
Sitting        54.86
SittingDown    62.31
Smoking        45.58
Waiting        42.50
WalkDog        47.61
Walking        31.99
WalkTogether   33.34
Average        44.83
mpjpe: 44.83

**Comment by alecda573** [comment]
@funnypig521 you are essentially right where you should be. They report 44.5 as the erro for the 81 frame model for cpn detections. 

.3mm difference is well within bound given stochastic nature of training an NN

you have the log for 351 frame model?

also any idea how to train on MPI dataset?

**Comment by Vegetebird** [comment]
Hi~Thanks for your interest fou our work. 

@alecda573 is right. The results reprocuced may depend on your machine. It has a little different. 

This is my trainning log for 351 frame
