### ISSUE TITLE
About the output and input of MHG

### ISSUE THREAD

**Issue by NanNingmalou** [Vegetebird/MHFormer#102]
Hello, I would like to ask if the 3 hypothesis generated by the MHG module are the same, or if they are three different hypothesis.Whether the 3 hypothesis output in CHI are the same

**Comment by Vegetebird** [comment]
Hi~There are three different hypothesis and they are not the same.

**Comment by eirtech** [comment]
Hi, 
Thanks for your great work. I am wondering if the three hypothesis output of CHI are accessible via Transformer class?
