### ISSUE TITLE
About Python version

### ISSUE THREAD

**Issue by Archives-RZ** [Vegetebird/MHFormer#103]
I want to ask why the version of python is 3.9. It doesn't match the version of PyTorch 1.7.1 and Torchvision 0.8.2

**Comment by k2room** [comment]
Try it on Python 3.8. It works.

**Comment by Vegetebird** [comment]
Hi~
On python3.9, it is OK for me to install PyTorch on 4090/3090 with
"pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html"

**Comment by Archives-RZ** [comment]
> 你好~ 在python3.9上，我可以在4090/3090上安装PyTorch，使用 “pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 -f [https://download.pytorch.org /whl/torch_stable.html](https://download.pytorch.org/whl/torch_stable.html) “

我觉得可能是我用Windows的问题，如果在Windows上直接用安装总会产生conflicts。我最后通过把每个对应版本的torch和torchvision通过离线下载再安装就可以，以及需要安装Visual Studio 2017的C++依赖，就可以在Window上运行了。

**Comment by Archives-RZ** [comment]
目前我产生了新的问题，我想知道不管是相机坐标系还是世界坐标系，您的坐标原点和您的XYZ轴都是沿着哪个方向建立的？

**Comment by Archives-RZ** [comment]
我还有一个问题，就是从数学的角度出发，是如何通过计算完成从二维到三维的坐标变换的计算的？我在paper中没有看到很详细的计算方式，或者是我理解不对，希望您能稍微详细的解释一下，十分感谢

**Comment by Vegetebird** [comment]
Hi~Perhaps you can visualize the data to examine the direction of the coordinate axis. The mapping from 2D to 3D is achieved through a learning method, which is fundamentally an ambiguous problem.
