### ISSUE TITLE
Joint and Keypoints number

### ISSUE THREAD

**Issue by MWLLER** [Vegetebird/MHFormer#104]
Thank you for your excellent work.
I encountered a problem while visualizing and obtaining the coordinates of each key point. Can I know what the joints corresponding to each keypoint are, and whether they are the same as those marked in the following figure.Thank you.
![b0e01ef8c24f089601be0213b300c9b](https://github.com/Vegetebird/MHFormer/assets/91045858/7b1a07c3-7716-4154-984b-11d4015d7344)

**Comment by Vegetebird** [comment]
Yes,  they are the same as those marked in your giving figure.

**Comment by MWLLER** [comment]
Thank you！
