### ISSUE TITLE
Human 3.6M dataset is unavailable to download! 

### ISSUE THREAD

**Issue by harshap-ai** [Vegetebird/MHFormer#108]
Hello, 
I tried creating an account at the official website of H3.6M (http://vision.imar.ro/human3.6m/description.php), but it's been a long time since I got a response. I was wondering if there was another way to get it? (Although the .npz files are present, would really like to have the videos/parsed images).

**Comment by Vegetebird** [comment]
Maybe you can use the Human3.6M images provided in [PoseNet](https://github.com/mks0601/3DMPPE_POSENET_RELEASE)
