### ISSUE TITLE
demo run reports matrix error

### ISSUE THREAD

**Issue by KungZell** [Vegetebird/MHFormer#110]
Hello  @Ha0Tang, thank you very much for the great project you and your team have provided, when running the demo, the following error occurs, how should I change it?
`Generating 2D pose...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "demo/vis.py", line 288, in <module>
    get_pose2D(video_path, output_dir)
  File "demo/vis.py", line 92, in get_pose2D
    keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
  File "C:\Users\MR G\Desktop\MHFormer-main\demo\lib\hrnet\gen_kpts.py", line 164, in gen_video_kpts
    keypoints = keypoints.transpose(1, 0, 2, 3)  # (M, T, N, 2) --> (T, M, N, 2)
ValueError: axes don't match array`

**Comment by rongmengmeng** [comment]
Did you solve the problem? I'm in the same situation.

**Comment by Vegetebird** [comment]
Maybe the error is caused by the first frame of the video not detecting a person.

**Comment by 835376431** [comment]
I encountered the same problem, is there any solution?

**Comment by Gausshy** [comment]
1. np.float() ---> float()
