### ISSUE TITLE
why rot = [0.1407056450843811, -0.1500701755285263, -0.755240797996521, 0.6223280429840088] in demo.py

### ISSUE THREAD

**Issue by APeiZou** [Vegetebird/MHFormer#113]
@Vegetebird    Hello, this is a great work，What I don't understand is that: why rot = [0.1407056450843811, -0.1500701755285263, -0.755240797996521, 0.6223280429840088] in demo.py and why are some values negative and where are their origins？

**Comment by Vegetebird** [comment]
see https://github.com/Vegetebird/MHFormer/issues/96
