### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by HulahaVla** [Vegetebird/MHFormer#12]
File "D:\work_py\MHFormer-main\demo\lib\hrnet\gen_kpts.py", line 163, in gen_video_kpts
    keypoints = keypoints.transpose(1, 0, 2, 3)  # (T, M, N, 2) --> (M, T, N, 2)
ValueError: axes don't match array

**Comment by alecda573** [comment]
@HulahaVla create seperate repo for demo and then place model directory from MHFormer-main inside of there and this will resolve issue. Issue is due to imports not being  recognized.

**Comment by Vegetebird** [comment]
Hi~Thanks for your interest fou our work. 
Following @alecda573  or re-downloading all the repo may resolve the issue.

**Comment by Realdr4g0n** [comment]
I am getting the same issue, so i debugged by pdb.
error caused from [here](https://github.com/Vegetebird/MHFormer/blob/7b17d005a1a4469d436578b06dc2e48c24d3a323/demo/vis.py#L272)

I think you should check out your video path passed into gen_kpts.py

**Comment by MolianWH** [comment]
Hi, I think the video should place in demo/video directory. And I tested it and passed.
