### ISSUE TITLE
training bug

### ISSUE THREAD

**Issue by yxdydgithub** [Vegetebird/MHFormer#20]
MHFormer/model/module/trans.py", line 43, in forward
    B, N, C = x.shape
ValueError: too many values to unpack (expected 3)

I print it!
ic| x.shape: torch.Size([128, 34, 351])
ic| x.shape: torch.Size([128, 34, 351])
ic| x.shape: torch.Size([128, 128, 34, 351])

**Comment by Vegetebird** [comment]
Could you test with our pretrained model?

**Comment by yxdydgithub** [comment]
Your pretrained model works fine.

**Comment by Vegetebird** [comment]
I train the model using the released code and it works well. Could you provide more detail about the bug or you redownload the repo?
