### ISSUE TITLE
An error occurred in the test model

### ISSUE THREAD

**Issue by afengen** [Vegetebird/MHFormer#24]
The pretrained model has been placed in the corresponding directory. 

(mhformer) D:\tujianfeng\MHFormer-main\MHFormer-main>python main.py --test --reload --previous_dir 'checkpoint/pretrained'
INFO: Testing on 543360 frames
Traceback (most recent call last):
  File "main.py", line 117, in <module>
    model_path = sorted(glob.glob(os.path.join(opt.previous_dir, '*.pth')))[0]
IndexError: list index out of range

**Comment by Vegetebird** [comment]
You could check the directory including the pretrained model, such as  'checkpoint/pretrained/xxx.pth', or you could directly use the absolute path.

**Comment by afengen** [comment]
> You could check the directory including the pretrained model, such as 'checkpoint/pretrained/xxx.pth', or you could directly use the absolute path.

Thank you very much! I directly use the absolute path, and the problem was solved.
