### ISSUE TITLE
why

### ISSUE THREAD

**Issue by lay111** [Vegetebird/MHFormer#25]
Traceback (most recent call last):
  File "demo/vis.py", line 277, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 139, in get_pose3D
    model_path = sorted(glob.glob(os.path.join(args.previous_dir, '*.pth')))[0]
IndexError: list index out of range

Why did such a mistake occur？

**Comment by Vegetebird** [comment]
You should check whether the pretrained model is in the args.previous_dir.

**Comment by lay111** [comment]
&nbsp; File "C:\Users\lay\anaconda3\envs\mhformer\lib\multiprocessing\context.py", line 322, in _Popen
&nbsp; &nbsp; return Popen(process_obj)
&nbsp; File "C:\Users\lay\anaconda3\envs\mhformer\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
&nbsp; &nbsp; reduction.dump(process_obj, to_child)
&nbsp; File "C:\Users\lay\anaconda3\envs\mhformer\lib\multiprocessing\reduction.py", line 60, in dump
&nbsp; &nbsp; ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe



why?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vegetebird/MHFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 上午8:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vegetebird/MHFormer] why (Issue #25)





 
You should check whether the pretrained model is in the args.previous_dir.
