### ISSUE TITLE
Gpu

### ISSUE THREAD

**Issue by lay111** [Vegetebird/MHFormer#27]
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 748.12 MiB already allocated; 0 bytes fre
e; 796.00 MiB reserved in total by PyTorch)
<img width="482" alt="微信图片_20220505211655" src="https://user-images.githubusercontent.com/104888740/166931076-e6caf8ab-d260-46e9-8bec-2ff741587966.png">

My batch_ size has been set to 1. Why does this error still occur? Do I need to change to a larger GPU

**Comment by Vegetebird** [comment]
Yeah, I use a 24GB 3090 GPU.
