### ISSUE TITLE
multiple gpu?

### ISSUE THREAD

**Issue by rambleramble** [Vegetebird/MHFormer#28]
saw this issue and we are trying to use multiple gpus?

https://github.com/Vegetebird/MHFormer/issues/27

Any advice?

**Comment by Vegetebird** [comment]
No problem, you can use "model = nn.DataParallel(model)" to use multiple gpus.

**Comment by anas-zafar** [comment]
Hi @Vegetebird , For multiple GPUs, the GPU seems to go to sleep at intervals within the epochs over different iterations. Any solution for this?
