### ISSUE TITLE
how to run inference in a single image or video with the pretrained models

### ISSUE THREAD

**Issue by Bobby-youngking** [Vegetebird/MHFormer#3]

**Comment by puppet101** [comment]
Same question

**Comment by Vegetebird** [comment]
You can refer to “https://github.com/facebookresearch/VideoPose3D” to run inference in a video with the pretrained models.

**Comment by Vegetebird** [comment]
Hi~ @puppet101 @Bobby-youngking 
We have released the demo and in-the-wild inference code. Plaese download the latest repo and refer to [demo](https://github.com/Vegetebird/MHFormer#demo).
