### ISSUE TITLE
Model of 81 and 243 

### ISSUE THREAD

**Issue by funnypig521** [Vegetebird/MHFormer#30]
Excuse me, could you please share your model of 81 frames and 243 frames? Thanks a lot!!!!!

**Comment by Vegetebird** [comment]
We have released the pretrained models of 81-frames, 243-frames, 351-frames. 
You can redownload the repo and pretrained models.

**Comment by funnypig521** [comment]
Thanks a lot,I got it!!!

**Comment by funnypig521** [comment]
Thanks a lot,I got it!!!
