### ISSUE TITLE
question about marking pictures in dataset

### ISSUE THREAD

**Issue by WaterS-MoYu** [Vegetebird/MHFormer#31]
hi，I finished reading your paper and I have a question, it seems that the Human3.6M and MPI-INF-3DHP dataset are used for evaluation, so does it mean that the training dataset is marked by yourself? I learned from other papers(e.g. blazepalm) that the widely used method is to use a 3d software to generate keypoints-marked dataset, then use this initial model to iteratively update.
您好，我阅读了您的文章，十分厉害！但是我有一个问题想请教你们，就是我看文章里面说的那两个数据集是用来评估的，我的理解是测试集，所以训练集是您在谷歌drive上的npz文件？是您自己标注的吗？因为我目前从其他文章了解到的方法是先用3d软件通过获取准确关节点的坐标生成数据集和初始模型，然后不停的迭代（标注其他数据集）。

**Comment by Vegetebird** [comment]
The annotations are provided by the dataset from [Human3.6M](http://vision.imar.ro/human3.6m/) website. 
The npz are  generated by [VideoPose3D](https://github.com/facebookresearch/VideoPose3D).

**Comment by WaterS-MoYu** [comment]
ok,thank you
