### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Michaelwhite34** [Vegetebird/MHFormer#33]
(mhformer) PS D:\mhformer> python demo/vis.py --video sample_video.mp4

Generating 2D pose...
  0%|▎                                                                                 | 1/291 [00:02<13:02,  2.70s/it]  1%|▌                                                                                 | 2/291 [00:03<06:45,  1.40s/it]  1%|▊                                                                                 | 3/291 [00:03<03:55,  1.22it/s]  1%|█▏                                                                                | 4/291 [00:03<02:35,  1.85it/s  2%|█▍                                                                                | 5/291 [00:03<01:50,  2.60it/s  2%|█▋   

Generating 2D pose successful!
Traceback (most recent call last):
  File "demo/vis.py", line 277, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 139, in get_pose3D
    model_path = sorted(glob.glob(os.path.join(args.previous_dir, '*.pth')))[0]
IndexError: list index out of range

**Comment by Michaelwhite34** [comment]
I change sorted(glob.glob(os.path.join(args.previous_dir, '*.pth')))[0] to 'demo/lib/checkpoint/pose_hrnet_w48_384x288.pth' and it gives 
Traceback (most recent call last):
  File "demo/vis.py", line 277, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 143, in get_pose3D
    model_dict[name] = pre_dict[name]
KeyError: 'norm_1.weight'

**Comment by Vegetebird** [comment]
The bug is fixed. You can redownload the repo and pretrained models.

**Comment by Vegetebird** [comment]
The model_path should be our pretrained model of MHFormer. You should put our model in 'checkpoint/pretrained/351' and use our original code.

**Comment by Michaelwhite34** [comment]
> The model_path should be our pretrained model of MHFormer. You should put our model in 'checkpoint/pretrained/351' and use our original code.

Generating 3D pose...
  0%|                                                                                          | 0/291 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo/vis.py", line 277, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 223, in get_pose3D
    show3Dpose( post_out, ax)
  File "demo/vis.py", line 72, in show3Dpose
    ax.set_aspect('equal')
  File "D:\anaconda3\envs\mhformer\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 312, in set_aspect
    "Axes3D currently only supports the aspect argument "
NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.

**Comment by Michaelwhite34** [comment]
> It works fine in matplotlib==2.2.2, may be you could try it.

But then how to export bvh ? I want to use it in 3d software.
