### ISSUE TITLE
multi-person pose estimation

### ISSUE THREAD

**Issue by Riverzxz** [Vegetebird/MHFormer#36]
hello ，author.I have a question that is mhformer can achieve multi-person pose estimation?

**Comment by Vegetebird** [comment]
This is a single-person method, the outputs are root-relative coordinates. But we can use some tips to achieve multi-person pose estimation, you can refer to https://github.com/fabro66/GAST-Net-3DPoseEstimation.

**Comment by mnauf** [comment]
@Vegetebird I know pelvis is the center of origin for Human3.6m. Can you please let me know where we have defined this in MhFormer code?

**Comment by Vegetebird** [comment]
# Remove global offset
pos_3d[:, 1:] -= pos_3d[:, :1] 

In, https://github.com/Vegetebird/MHFormer/blob/179ed65bd86dc7674e16bf31a7dfb4f4bc3ed172/common/load_data_hm36.py#L56

**Comment by Ared521** [comment]
> hello ，author.I have a question that is mhformer can achieve multi-person pose estimation?

Hi, Have you implemented multi-person pose estimation yet?
