### ISSUE TITLE
Format of data_3d_h36m.npz

### ISSUE THREAD

**Issue by mnauf** [Vegetebird/MHFormer#37]
Does data_3d_h36m.npz contain x,y,z coordinates in meters? or they are normalized?

**Comment by mnauf** [comment]
I understand that originally Human3.6 dataset contains XYZ coordinates wrt pelvis are in mm. Is it the same for this preprocessed file?

**Comment by Vegetebird** [comment]
The data_3d_h36m.npz is processed by [VideoPose](https://github.com/facebookresearch/VideoPose3D), contain x,y,z coordinates in meters, are not normalized, are in world coordinates.
