### ISSUE TITLE
KeyError: 'norm_1.weight'

### ISSUE THREAD

**Issue by yancccc** [Vegetebird/MHFormer#39]
python demo/vis.py --video sample_video.mp4

Generating 2D pose...
100%|███████████████████████████████████████████| 25/25 [00:05<00:00,  4.48it/s]
Generating 2D pose successful!
Traceback (most recent call last):
  File "demo/vis.py", line 280, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 146, in get_pose3D
    model_dict[name] = pre_dict[name]
KeyError: 'norm_1.weight'

 model_dict = model.state_dict()
    #model_path = sorted(glob.glob(os.path.join(args.previous_dir, '*.pth')))[0]
    model_path ='/home/ycc/pose/MHFormer-main/checkpoint/pretrained/pose_hrnet_w48_384x288.pth'

**Comment by Vegetebird** [comment]
The model_path should be our pretrained model of MHFormer. You should put our model in 'checkpoint/pretrained/351' and use our original code.
