### ISSUE TITLE
Maybe a small error in papers

### ISSUE THREAD

**Issue by Whiskysu** [Vegetebird/MHFormer#42]
Hi, Thanks for your great work and published code! But When I read the I found that in **'Supplementary Material -> A.Multi-Head Cross-Attention**’has an small error.**[paper url](https://arxiv.org/pdf/2111.12707.pdf) 
I think it should be 'linearly' instead of 'inearly'**.As show in the picture.
![图片](https://user-images.githubusercontent.com/46953515/170873542-fd0dbcbf-dc5e-43f7-a5b8-bb255968c114.png)

**Comment by Vegetebird** [comment]
Thanks for pointing out the error! We will revise it.
