### ISSUE TITLE
What's the meaning of  "center Frame"?

### ISSUE THREAD

**Issue by Whiskysu** [Vegetebird/MHFormer#43]
Hi，Cloud you tell me what the "center Frame" means as show in the following picture.
Supposed the input frame is 9, Dose the MHFomer uses the all 9 frames to predict the first frame's 3D Pose, just use the other 8 frames to make the first frame's  3D Pose more accurate, then for the second until ninth frame's 3D Pose?
![图片](https://user-images.githubusercontent.com/46953515/171010080-194e465f-df15-4676-8754-8f726b04cdc5.png)

**Comment by Vegetebird** [comment]
The center frame means the middle of a sequence. If the input frame is 9, MHFomer can output 9-frame 3D poses, but we select the 4-th (center) frames to evaluate the performance.
