### ISSUE TITLE
Questions about the vis.py code

### ISSUE THREAD

**Issue by anas-zafar** [Vegetebird/MHFormer#45]
Great work! Can you please explain what is happening in the code segment below and why do we need to flip the joints @Vegetebird 

## estimation
        output_3D_non_flip = model(input_2D[:, 0])
        output_3D_flip = model(input_2D[:, 1])

        output_3D_flip[:, :, :, 0] *= -1
        output_3D_flip[:, :, joints_left + joints_right, :] = output_3D_flip[:, :, joints_right + joints_left, :]

        output_3D = (output_3D_non_flip + output_3D_flip) / 2

**Comment by Vegetebird** [comment]
This is horizontal flip augmentation same as [1], which flips the left and right arm and leg joints, and inverses the z-dimension of all joints. 

[1] Pavllo et al. 3D human pose estimation in video with temporal convolutions and semi-supervised training, CVPR 2019.
