### ISSUE TITLE
About Visualizing Results

### ISSUE THREAD

**Issue by dxnana** [Vegetebird/MHFormer#46]
First of all thanks to the author for the code!
I'm having some trouble with this code and looking forward to your help.
How can I visualize the results of the human3.6 data, or is there anything I need to modify in vis.py?

**Comment by Vegetebird** [comment]
You can prepare a human3.6 video as the in-the-wild video and use 'vis.py' to visualize the 3D keypoints. (based on YOLOv3 and HRNet). 
Or you can use 'main.py' to test the model to get the outputs (based on CPN provided by ata_2d_h36m_cpn_ft_h36m_dbb.npz) and refer to 'vis.py' show3Dpose() to visualize the 3D keypoints.
