### ISSUE TITLE
error in vis.py

### ISSUE THREAD

**Issue by henbucuoshanghai** [Vegetebird/MHFormer#48]
python demo/vis.py --video sample_video.mp4

Generating 2D pose...
100%|█████████████████████████████████████████| 291/291 [00:19<00:00, 14.91it/s]
Generating 2D pose successful!
['checkpoint/pretrained/351/model_4294.pth']

Generating 3D pose...
  0%|                                                   | 0/291 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo/vis.py", line 279, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 225, in get_pose3D
    show3Dpose( post_out, ax)
  File "demo/vis.py", line 72, in show3Dpose
    ax.set_aspect('equal')
  File "anaconda3/envs/lili/lib/python3.8/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 323, in set_aspect
    raise NotImplementedError(
NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.

**Comment by henbucuoshanghai** [comment]
I download the code ,and change nothing, tks

**Comment by henbucuoshanghai** [comment]
i will try it tks

**Comment by MWLLER** [comment]
hello，I have encountered the same problem. How did you solve it.
