### ISSUE TITLE
算法细节

### ISSUE THREAD

**Issue by henbucuoshanghai** [Vegetebird/MHFormer#51]
检测后得到2d kps，请问2d kps输出npz保存的是针对原图大小的数值xy？score是kps的得分？在0，1之间？
2d维度为什么换为1,351,17,2？ 某一帧的17,2维度怎么扩展到251的呢？
感谢！

**Comment by henbucuoshanghai** [comment]
351

**Comment by henbucuoshanghai** [comment]
to test on real-time video in camera,Is it better to train a model which the 351th  frame is the current frame? 
the last frame as the last resout,not the 351//2?

**Comment by Vegetebird** [comment]
Please see https://github.com/Vegetebird/MHFormer/issues/13
