### ISSUE TITLE
normalize_screen_coordinates? why ?

### ISSUE THREAD

**Issue by henbucuoshanghai** [Vegetebird/MHFormer#54]
def normalize_screen_coordinates(X, w, h):
    assert X.shape[-1] == 2
    
    return X / w * 2 - [1, h / w]

why is X / w * 2 - [1, h / w]?  it is must be it in 3d pose?

**Comment by Vegetebird** [comment]
Normalize so that [0, w] is mapped to [-1, 1], while preserving the aspect ratio following [VideoPose](https://github.com/facebookresearch/VideoPose3D).

**Comment by henbucuoshanghai** [comment]
tks，I see.&nbsp; by default in 3d pose?


351 frames in the model?why 351?it is too large,I change it to 71 and train the model?is it ok?
tks

**Comment by Vegetebird** [comment]
Yes, it is a standard normalization in 3D HPE. 
You can train a 81-frame model and we have released the pretrained model of 81-frame.
