### ISSUE TITLE
some error I met when I try to test my own video

### ISSUE THREAD

**Issue by ycj1124** [Vegetebird/MHFormer#55]
thank you for your work!I have tried the demo video your offer in the demo/video folder.but when I try to replace the video with my own video,it happened to occur the error as follows:
![2022-06-17 12-11-48 的屏幕截图](https://user-images.githubusercontent.com/55937464/174223353-b1f78c89-3180-41f6-8b34-d69500e54005.png)
could you tell me what may be the possible problem?should I make the resolution of mine the same as the demo video?
or should I take a outdoor video instead of taking indoor?
I would be really appreciated if you could help me ！ thank you!

**Comment by Vegetebird** [comment]
You can send the video to my email "wenhaoli@pku.edu.cn" and I will try it to find the bug.

**Comment by ycj1124** [comment]
alright ，thank you sir，I will send to you later.



发自我的iPhone


------------------ Original ------------------
From: Wenhao Li ***@***.***&gt;
Date: Fri,Jun 17,2022 3:00 PM
To: Vegetebird/MHFormer ***@***.***&gt;
Cc: ycj1124 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Vegetebird/MHFormer] some error I met when I try to test my ownvideo (Issue #55)





 
You can send the video to my email ***@***.***" and I will try it to find the bug.

**Comment by Vegetebird** [comment]
Hi~I do not receive the video in my email.

**Comment by ycj1124** [comment]
> I do not understand it clearly. If you want to use our pretrained model, the code of our model should not be changed.

well ,I mean I do not use your pretrained model .If I want to change the model ,which .py should I change?thank you!

**Comment by Vegetebird** [comment]
The files in './model' directory could be changed

**Comment by ycj1124** [comment]
> The all files in './model' directory could be changed

thank you.and should I change the command line when typing in the terminal after I change the code?

**Comment by Vegetebird** [comment]
The command line may be used the same
