### ISSUE TITLE
how to get the coordinate data?

### ISSUE THREAD

**Issue by ycj1124** [Vegetebird/MHFormer#60]
after your instructions I can successfully get the MPJPE rate and the output video like this:

![2022-06-30 10-14-43 的屏幕截图](https://user-images.githubusercontent.com/55937464/176578296-5d1867d1-0a21-4f26-98dd-af27a29de250.png)

and I wonder whether I could get the coordinate data of the point,such as the (x,y) of the human joint? which .py could I run to make it possible?
thank you very much

**Comment by Vegetebird** [comment]
The 'input_2D' contains coordinate data of input (x,y) joints.
