### ISSUE TITLE
the 81 frames pretrained model?

### ISSUE THREAD

**Issue by henbucuoshanghai** [Vegetebird/MHFormer#61]
where is it? tks

**Comment by wenwen12321** [comment]
I found the google link from the folder of "checkpoint/pretrained"
[google link](https://drive.google.com/drive/folders/1UWuaJ_nE19x2aM-Th221UpdhRPSCFwZa)

**Comment by henbucuoshanghai** [comment]
very kind of you,  I donwload the 81,243 ,351, test them ,resout is nice.
but
1: the 81frames model is faster than 351? flops is smaller?
2:the  google link folder has 27 frames model , I test it ,error,why?
Generating 2D pose successful!
['checkpoint/pretrained/27/model_4590.pth']
Traceback (most recent call last):
  File "demo/vis.py", line 291, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 147, in get_pose3D
    model_dict[name] = pre_dict[name]
KeyError: 'embedding_1.weight'

**Comment by Vegetebird** [comment]
Please redownload the repo, it can works well.
