### ISSUE TITLE
代码细节

### ISSUE THREAD

**Issue by qiqiApink** [Vegetebird/MHFormer#62]
您好，请问一下您的paper里说到预测输出的是中间一帧，但是为什么代码里输出的是和输入序列长度一样的序列？所以预测结果到底是中间帧还是序列呢

**Comment by Vegetebird** [comment]
Please see https://github.com/Vegetebird/MHFormer/issues/13.
MHFormer can output a sequence of 3D poses and we just select the pose of center frame to evaluate the performance.
