### ISSUE TITLE
Regarding the 2D Predictor

### ISSUE THREAD

**Issue by anas-zafar** [Vegetebird/MHFormer#63]
Thank you for the amazing work! I had a question regarding the 2D Predictor that MHFormer is using as input. Originally, the Cascaded Pyramid Network for Multi-Person Pose Estimation paper is using COCO Dataset for training. Is MHFormer using pretrained weights from that paper or is it retrained for Human3.6 Dataset? Thank you

**Comment by Vegetebird** [comment]
The CPN is finetuned on Human3.6 by https://github.com/facebookresearch/VideoPose3D

**Comment by anas-zafar** [comment]
Got it. Thank you for the prompt reply
