### ISSUE TITLE
Estimated 2D Kpts

### ISSUE THREAD

**Issue by anas-zafar** [Vegetebird/MHFormer#64]
Hi @Vegetebird ,
I have a confusion regarding the 2D kpts. Can you please explain how the 2D kpts are being computed in the snippet below:
![snippet](https://user-images.githubusercontent.com/65417556/179737126-b4627b4b-69df-4a0a-9f9a-3c468653d5a2.PNG)

I went through your paper, it seems you are using CPN finetuned on Human3.6m, but in the code base Hrnet pose is being used? Thank you

**Comment by Vegetebird** [comment]
In the wild inputs, we use HRnet to get 2D poses, but the model is trained using CPN finetuned on Human3.6m

**Comment by anas-zafar** [comment]
@Vegetebird is HRnet also fine tuned on Human3.6m for MHFormer?

**Comment by Vegetebird** [comment]
No, the HRNet is trained on COCO.

**Comment by anas-zafar** [comment]
Got it. Thank you @Vegetebird
