### ISSUE TITLE
Is it possible to use YOLOv7 ?

### ISSUE THREAD

**Issue by Arkitect-z** [Vegetebird/MHFormer#65]
非常棒的工作！
我正在拼命学习你们的研究并且尝试将其应用于实际领域。

我想问的是，
1. output文件夹下的'input_2D'文件夹内是否已经是3D 人体姿势估计的结果（也就是你们论文中所描述的主要工作生成的结果）？因为我想将其用在优化虚拟人物动作中。
2. 目前使用的是略显“古老”的YOLOv3和体积很大的HRNet来工作，是否有可能将其换成新的YOLOv7和Lite-HRNet，以加快识别姿态的速度，并最终实现实时识别和多目标同时识别？

如果可行的话，能否给我讲一下修改方法？例如如何生成“ YOLOv7.weights”文件，以及能否直接在github仓库中下载Lite-HRNet来替换使用？

请原谅我作为一个cv领域的初学者可能提问过于小白，感谢您的耐心

Great Great Job!
I'm trying my best to study your research and try to apply it in real world.

What I want to ask is,
1. Is the 'input_2D' folder that in the ‘output’ folder the result of 3D human pose estimation(that is, the main work in your paper)? Because I want to use it in optimizing avatar motivation.
2. Currently working with a slightly "old" YOLOv3 and a large HRNet, is it possible to replace it with the new YOLOv7 and Lite-HRNet to speed up the recognition of poses and finally achieve real-time recognition and multi-tasking? target at the same time?

If possible, can you tell me how to modify it? For example, how to generate the "YOLOv7.weights" file, and can I download Lite-HRNet directly in the github repository to replace it?

Please forgive me as a beginner in cv area for asking such primary questions, thank you for your patience.

**Comment by henbucuoshanghai** [comment]
工作量好大

**Comment by Vegetebird** [comment]
'input_2D' is the 2D poses detected by HRNet. 

The demo code is following "https://github.com/fabro66/GAST-Net-3DPoseEstimation", which uses YOLOv3 and HRNet.
