### ISSUE TITLE
GPU Not being utilized within iterations (Multi GPU)

### ISSUE THREAD

**Issue by anas-zafar** [Vegetebird/MHFormer#66]

**Comment by Vegetebird** [comment]
I use the "model = nn.DataParallel(model)" to use multi GPU. It works well. I do not know how to solve your issue.

**Comment by anas-zafar** [comment]
@Vegetebird can you please point me at what line are you adding this to in the code base?

**Comment by Vegetebird** [comment]
I add "model = nn.DataParallel(model)" before https://github.com/Vegetebird/MHFormer/blob/fcf238631016f906477ec9c1d17582097ecf9803/main.py#L131
