### ISSUE TITLE
trans_hypothesis代码以及MCA的计算方式

### ISSUE THREAD

**Issue by z0911k** [Vegetebird/MHFormer#68]
您好，我想向您请教两个问题。
1）代码/model/module/trans_hypothesis.py中的第145、146、147行，第146行中的x_1按照论文不应该是第145行中计算得到的x_1吧？以及第147行。
![image](https://user-images.githubusercontent.com/76470990/185106964-1fe5c174-a356-42a7-bc33-252d9e8ba63e.png)
2）您论文中的实验提到了不同假设个数时的结果，当假设个数不是3时，MCA应该怎么计算呢？

**Comment by Vegetebird** [comment]
The code simplifies this parallel operation. You can clone these values before feeding them to the MCA, and the performance will be similar. 
When M=2, we use q!=k=v.

**Comment by z0911k** [comment]
What about when M=4？

**Comment by Vegetebird** [comment]
When M=4, we use 4 attention blocks to caculate cross attention among selected 3 values for simplify. Sincle we find that too more attention blocks may lead to overfitting.
