### ISSUE TITLE
In the wild inference?

### ISSUE THREAD

**Issue by alecda573** [Vegetebird/MHFormer#7]
How do you guys handle in the wild inference since you only release models that have been trained on cpn_ft_detections that are already in line with the h36m skeleton?

**Comment by Vegetebird** [comment]
We use HRNet to get 2D pose inputs and convet them to h36m format. 
Visualization and  in-the-wild inference code will be coming soon.

**Comment by alecda573** [comment]
@Vegetebird I see so the detection results you report in the paper are those fine tuned to h36m or did you use hrnet detections?

**Comment by Vegetebird** [comment]
The performace report in the paper are using cpn_ft_detections following [VideoPose](https://github.com/facebookresearch/VideoPose3D). 
For in the wild inference, following [GAST-Net](https://github.com/fabro66/GAST-Net-3DPoseEstimation), the model is trained on cpn_ft_detections and the input 2D poses are predited by HRNet.

**Comment by alecda573** [comment]
@Vegetebird Thanks for the response. One question I had about your Strided transformer paper is what is being interpreted from the compression ratio calculated in the complexity analysis section?

**Comment by Vegetebird** [comment]
Hi~Sorry for the late reply.

The compression ratio calculated shows our method can reduce the computation cost of Transformers.

**Comment by Vegetebird** [comment]
Hi~ @alecda573 @akk-123 
We have released the demo and in-the-wild inference code. Plaese download the latest repo and refer to [demo](https://github.com/Vegetebird/MHFormer#demo).
