### ISSUE TITLE
Can you share the training and testing codes of the 3dhp dataset?

### ISSUE THREAD

**Issue by ClimberY** [Vegetebird/MHFormer#70]
I used the script provided by the P-STMO model(https://github.com/paTRICK-swk/P-STMO) to train and test the MHFormer model on the 3dhp dataset. The average value of PCK and AUC indexes obtained was 20 and mpjpe was 300, but the results were very unreliable.

**Comment by qiqiApink** [comment]
Have u solve this probelm?

**Comment by ClimberY** [comment]
> @ClimberY Have u solve this probelm?

No, I haven't found a solution yet.

**Comment by Vegetebird** [comment]
Sorry, we do not have the plan to release this code. You can train our model in their repo, maybe it can work well.

**Comment by Whj-cv** [comment]
> > @ClimberY Have u solve this probelm?
> 
> No, I haven't found a solution yet.

Have you solved this problem now?

**Comment by MehwishG** [comment]
@ClimberY have you solved this problem, I am getting same error i tried with frames=81,27 and 9. but at test time MPJPE is very large whereas train-MPJPE is decreasing

**Comment by GloryyrolG** [comment]
> Sorry, we do not have the plan to release this code. You can train our model in their repo, maybe it can work well.

Hi @Vegetebird , thanks for your great work. May I ask if the 58.0 MPJPE results on MPI-INF-3DHP are cross-dataset, \ie, the model is trained on Human3.6M? According to what you said, it seems it is a result of training on 3DHP?
