### ISSUE TITLE
How to get the transition of root?

### ISSUE THREAD

**Issue by jinfagang** [Vegetebird/MHFormer#72]
It looks like there is no output of transition of root joint?

**Comment by Vegetebird** [comment]
This method ouputs relative coordinates with respect to the root joint. 
You can refer to [1] to train a trajectory model and output the coordinates of the root joint to achieve global positions. 

[1] 3D human pose estimation in video with temporal convolutions and semi-supervised training, CVPR 2019.

**Comment by jinfagang** [comment]
@Vegetebird hi, thank u for suggestion. Does VideoPose3d outputs global 3d pose directly? It seems work from 2 years ago, does there any further work on this direction? ( I found SMPL based model always not very good on translations, just wonder if VideoPose3d like model could be the cure of this problem)

**Comment by Vegetebird** [comment]
The single-view 3D human pose estimation method is hard to estimate global coordinates. You can refer to some multi-view methods.
