### ISSUE TITLE
IndexError: list index out of range?

### ISSUE THREAD

**Issue by TomCatOnline** [Vegetebird/MHFormer#73]
When i tried to train a new model, this error occurred:

File "main.py", line 117, in <module>
  model_path = sorted(glob.glob(os.path.join(opt.previous_dir, '*.pth')))[1]
IndexError: list index out of range

I wonder why and how i can fix this,please?

**Comment by Vegetebird** [comment]
The bug has been fixed ago. You can redownload the repo.

**Comment by TomCatOnline** [comment]
Fixed.Thanks for your great work!
