### ISSUE TITLE
Missing reference paper that has better results on `Human3.6M` than `MHFormer`?

### ISSUE THREAD

**Issue by krenerd** [Vegetebird/MHFormer#74]
The paper "[Occlusion-Aware Networks for 3D Human Pose Estimation in Video](https://openaccess.thecvf.com/content_ICCV_2019/papers/Cheng_Occlusion-Aware_Networks_for_3D_Human_Pose_Estimation_in_Video_ICCV_2019_paper.pdf)"[1] published in ICCV 2019 achieves 42.9 MPJPE(protocol 1) and 32.8 P-MPJPE(protocol 2) while your paper[2] achieves 43.0 MPJPE and 30.5 P-MPJPE. While `MHFormer` claim state-of-the-art performance on Human3.6M 3D pose estimation, their method seem to outperform `MHFormer`. It seems that your paper doesn't compare against their results. If I'm haven't mistaken, [1] is not listed in the reference. 

Both tables seem to compare performance in the same setting(monocular 3d pose estimation) and also since they both show same numbers for [3], as underlined in red.

![image](https://user-images.githubusercontent.com/48239275/188284745-758ce5cf-4b11-41f3-a55b-d3e3a6a9dccf.png)

 ↑ Table from [1] 

![image](https://user-images.githubusercontent.com/48239275/188284736-743cf05f-3474-4f9f-98a5-be3484b15e49.png)

 ↑ Table from your paper[2]

I think your paper should be revised so that it contain comparisons against [1]. Please correct me if I misunderstood something. 

[1] Cheng, Y., Yang, B., Wang, B., Yan, W., & Tan, R. T. (2019). Occlusion-aware networks for 3d human pose estimation in video. In Proceedings of the IEEE/CVF international conference on computer vision (pp. 723-732).

[2] Li, W., Liu, H., Tang, H., Wang, P., & Van Gool, L. (2022). Mhformer: Multi-hypothesis transformer for 3d human pose estimation. In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (pp. 13147-13156).

[3] Pavllo, D., Feichtenhofer, C., Grangier, D., & Auli, M. (2019). 3d human pose estimation in video with temporal convolutions and semi-supervised training. In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (pp. 7753-7762).

**Comment by krenerd** [comment]
Reading the paper[1] again, I noticed that their 2D poses were generated using a Stacked Hourglass Network while this repo uses CPN keypoints from [3]. Though results from [3] suggest that CPN keypoints were better than Stacked Hourglass Network keypoints, maybe the improvements in [1] came from better 2D pose estimators. 

Although I'm very curious about how [1] compares with modern methods, I guess there is no real way to compare since the authors didn't release code and doesn't elaborate on how they fine tuned the 2D pose estimator on the paper. 

Sorry for the confusion 🙏 I really liked your paper 😎

**Comment by Vegetebird** [comment]
Their method takes images as input and trains the 2D pose estimator along with the 3D network end-to-end, while our method takes 2D poses estimated by a pretrained 2D detector as input. 

So their method is the image-based method and our method is the 2D-to-3D pose lifting method.
