### ISSUE TITLE
How can (x,y,z) 3D points be extracted from 3dpose?

### ISSUE THREAD

**Issue by ThanosUTH** [Vegetebird/MHFormer#81]
Hello, excellent work.

How can (x,y,z) 3D points be extracted from 3dpose?
It provides only the 2D coordinates ini .npyfile.

Thanks a lot

**Comment by Vegetebird** [comment]
You can save the vis
https://github.com/Vegetebird/MHFormer/blob/fcf238631016f906477ec9c1d17582097ecf9803/demo/vis.py#L224
to .npy file
