### ISSUE TITLE
Hello, I can only get the result of 'CPN' when testing with the pre training model you provided. If I want to get the result of 'GT', what should I do?

### ISSUE THREAD

**Issue by Whj-cv** [Vegetebird/MHFormer#84]
Hello, I can only get the result of 'CPN' when testing with the pre training model you provided. If I want to get the result of 'GT', what should I do?

**Comment by Vegetebird** [comment]
You can change the https://github.com/Vegetebird/MHFormer/blob/fcf238631016f906477ec9c1d17582097ecf9803/common/opt.py#L16
to 'gt'.
