### ISSUE TITLE
data transform of joints

### ISSUE THREAD

**Issue by foocker** [Vegetebird/MHFormer#87]
can the 17 joints translate to smpl 23+1 joints?

**Comment by Vegetebird** [comment]
J24_NAME = ('R_Ankle', 'R_Knee', 'R_Hip', 'L_Hip', 'L_Knee', 'L_Ankle', 'R_Wrist', 'R_Elbow', 'R_Shoulder', 'L_Shoulder',
'L_Elbow','L_Wrist','Neck','Top_of_Head','Pelvis','Thorax','Spine','Jaw','Head','Nose','L_Eye','R_Eye','L_Ear','R_Ear')

H36M_J17_NAME = ( 'Pelvis', 'R_Hip', 'R_Knee', 'R_Ankle', 'L_Hip', 'L_Knee', 'L_Ankle', 'Torso', 'Neck', 'Nose', 'Head',
                  'L_Shoulder', 'L_Elbow', 'L_Wrist', 'R_Shoulder', 'R_Elbow', 'R_Wrist')

The H36M_J17 loss some SMPL_J24 joints, it only can approximate map. You can refer to [https://github.com/open-mmlab/mmhuman3d/blob/main/docs/customize_keypoints_convention.md] and [https://github.com/open-mmlab/mmhuman3d/blob/main/docs/keypoints_convention.md] for more details.
