### ISSUE TITLE
parameter question

### ISSUE THREAD

**Issue by zhaoduanlu** [Vegetebird/MHFormer#89]
Does anybody know what p1,p2 stands for in the code？

**Comment by Vegetebird** [comment]
Protocol 1 (P1) is the MPJPE which measures the mean Euclidean distance between the ground truth and estimated joints in millimeters. 
Protocol 2 (P2) is the MPJPE after aligning the predicted 3D pose with the ground truth using translation, rotation, and scale (P-MPJPE). 
You can refer to "4.1. Datasets and Evaluation Metrics" in our paper for more details.
