### ISSUE TITLE
MPI-INF-3DHP preprocessing code?

### ISSUE THREAD

**Issue by alecda573** [Vegetebird/MHFormer#9]
Can you please share your code  to preprocess this dataset?

**Comment by Vegetebird** [comment]
Hi~

I will release the code about 3DHP. You can also use other MPI-INF-3DHP code for preprocessing.

**Comment by alecda573** [comment]
@Vegetebird When I’ve used other processing scripts I’ve been unable to reproduce reported metrics for cross dataset evaluation. Could you possibly outline what was your procedure on MPI?

As an aside, could you share the addition wild videos you used in the paper for the qualitative analysis in the appendix?

**Comment by Vegetebird** [comment]
Our setting follows [1,2] and you can refer to [Anatomy3D_issue5]('https://github.com/sunnychencool/Anatomy3D/issues/5'.)  And we don't use cross dataset evaluation like some single-frame based method. We train our model on 3DHP and test it on 3DHP.  

[1] Chen T, Fang C, Shen X, et al. Anatomy-aware 3D Human Pose Estimation with Bone-based Pose Decomposition. IEEE Transactions on Circuits and Systems for Video Technology, 2021.
[2] Zheng C, Zhu S, Mendieta M, et al. 3D human pose estimation with spatial and temporal transformers. ICCV, 2021.

**Comment by alecda573** [comment]
@Vegetebird thanks for the clarification that you do not do cross-dataset evaluation. Do you train on the GT 2D input for MPI or do you have a  seperate file containing detections?

**Comment by Vegetebird** [comment]
Following them, we train on the GT 2D input.
