### ISSUE TITLE
Something about vis.py

### ISSUE THREAD

**Issue by Ared521** [Vegetebird/MHFormer#90]
Hi author, I'm running vis.py, and I want to get three-dimensional coordinate information x,y,z. I see there are post_out and output_3D in the code, may I ask which coordinate is it? What's the difference between these two parameters?

**Comment by Vegetebird** [comment]
The output_3D is in camera coordinate, and post_out is in world coordinate. Maybe post_out is more appropriate for you.

**Comment by Ared521** [comment]
> The output_3D is in camera coordinate, and post_out is in world coordinate. Maybe post_out is more appropriate for you.

OK, Thank you very much.

**Comment by jerriebright** [comment]
Hey! I have a query in regard to the coordinate system. Did you use World or Camera coordinate pose data for training? Also, will using the pose data in different coordinate systems affect the model's performance?

**Comment by mnauf** [comment]
@jerriebright The author has used a camera coordinate system for training. The models predict 3d joint locations in the camera coordinate system, and later the author explicitly converts them to a world coordinate system. This step is optional

**Comment by jerriebright** [comment]
Hi @mnauf , thank you!
