### ISSUE TITLE
Why converted 3d joint locations in world coordinate system to camera coordinate system during training?

### ISSUE THREAD

**Issue by mnauf** [Vegetebird/MHFormer#93]
Why did you prefer to convert 3D joint locations in the world coordinate to a camera coordinate system?

**Comment by mnauf** [comment]
I understand that predicting joints in camera coordinates is often a natural choice when using 2D pose estimates as input to the 3D pose estimation system. 2D poses are typically predicted in camera coordinates, and so predicting 3D poses in the same coordinate system makes it easier to combine the 2D and 3D pose estimates. 

But then why do you convert camera coordinate predictions back to the world coordinate system in vis.py?

**Comment by Vegetebird** [comment]
In vis.py, it is OK to visualize the 3D joints in camera coordinates. In order to improve the comprehensibility of the visualization, we convert them to the world coordinate system.
