### ISSUE TITLE
Why rot is these four numbers？

### ISSUE THREAD

**Issue by tongwei0828** [Vegetebird/MHFormer#96]
Hello, it's a greate work. But i have some questions, in demo/vis.py, rot is a rotation matrix, why rot is these four numbers? Can it be other numbers?
![image](https://user-images.githubusercontent.com/102271146/221076742-a3713ecc-5682-4ac7-af78-edbd83b24555.png)

**Comment by Vegetebird** [comment]
We use a camera extrinsic parameter provided by Human3.6M (https://github.com/Vegetebird/MHFormer/blob/fcf238631016f906477ec9c1d17582097ecf9803/common/h36m_dataset.py#L59). 
I can be other numbers.
