### ISSUE TITLE
About 2D attitude detection.

### ISSUE THREAD

**Issue by Ared521** [Vegetebird/MHFormer#97]
Thank you for your great work. I have a question to ask. I see that the 2D pose detection in your code uses HRNet, which can only detect a single person. If I want to detect the 3D pose of multiple people, can I use HigherHRNet instead? , detect the 2D poses of multiple people, and then use MHFormer to detect the 3D poses of them?

**Comment by Vegetebird** [comment]
You can use HigherHRNet, or alternatively, you can detect multiple people's bounding boxes using YOLOv3 and feed each bounding box into HRNet.

**Comment by Ared521** [comment]
> Yes, you can use HigherHRNet. Alternatively, you can detect the bounding boxes of multiple people using YOLOv3, track each person, and then feed the tracked bounding boxes of each person into HRNet.

OK, Thank you!
